# custom properties
build.version=2.0

accounts.message=Bank accounts related local QA APIs
accounts.contactDetails.name=Smith Ray - QA Lead
accounts.contactDetails.email=john@example.com
accounts.onCallSupport=(666) 265-3765,(666) 734-8371
