spring.application.name=config-server

#spring.profiles.active=native
#spring.cloud.config.server.native.search-locations=classpath:config

spring.profiles.active=git
spring.cloud.config.server.git.uri=https://github.com/dimihris/product-configs.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.timeout=5
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.force-pull=true

# hardcoded for simplicity, can be configured with env variables or cli arguments etc...
encrypt.key=KwqGpA+;x?6^dvkjr6JFHPvdH.V9R_$V

server.port=8071

management.endpoints.web.exposure.include=*

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
